export const locale = lang => (ru,en) => lang === 'en' ? en : ru;
export const root = lang => lang === 'en' ? '/en/' : '/';
const entries = [
['Standard','140 × 200 cm bed','Courtyard windows','A compact room for one guest, with a desk, tea station and a quiet courtyard outlook.','Rooms are on floors 2–5.'],
['Superior','Double bed or two single beds','Courtyard windows','A light room for two, with a desk and space to unwind. Windows face the hotel’s inner courtyard.','State your bed preference when booking. Availability depends on the particular room.'],
['Deluxe','Double bed and a sofa bed or chair bed','More space, a courtyard view','A room with an extra place to relax, accommodating up to three guests. Windows face the inner courtyard.','Layouts and the type of extra bed vary within this category.'],
['Deluxe Grand','Double or twin beds and a sofa','Space for up to four guests','A spacious room with a sofa and room for an extra bed. Windows overlook the courtyard or Gorokhovaya Street.','The fourth guest uses an extra bed. Ask the hotel about connecting rooms.'],
['Studio','180 × 200 cm double bed','Kitchenette and bathtub','A room for a leisurely stay, with a kitchenette, hob, microwave and tableware. Windows face the courtyard or Gorokhovaya Street.','Rooms are on floors 2 and 3.'],
['Admiralty Deluxe','Double or twin beds and a sofa','Admiralty and garden views','Windows overlook the Admiralty and Alexander Garden. There is a sofa and space for an extra bed.','Size, layout and bathroom configuration vary. Contact the hotel about a specific room.'],
['Family','Double bed and a sofa bed','Two separate rooms','A bedroom and a separate living room give the family more space. Rooms on regular floors face the courtyard; attic rooms overlook the sky.','Rooms are on floors 2, 4 and 5. Let the hotel know if the floor or attic layout matters to you.'],
['Favourite Suite','Double bed and a sofa bed','Historic stucco and a kitchen','A third-floor suite with restored stucco, four-metre ceilings and a kitchen area. Windows overlook Gorokhovaya Street.','The bathroom has a window and a corner bathtub. The suite is one spacious room.'],
['Admiralty Suite','Double bed and a sofa bed','Two rooms overlooking the Admiralty','A separate bedroom and living room, with views of the Admiralty and Alexander Garden. Several layouts are available on different floors.','Only some suites have a kitchen area. It is not guaranteed by the category; arrange it with the hotel.'],
['City View Suite','Double bed and a sofa bed','A generous living room on Gorokhovaya Street','A two-room suite with a separate bedroom and a large living room. Windows overlook Gorokhovaya Street.','Only the fourth-floor version has a kitchen. Layout and extra beds must be agreed with the hotel.'],
['Sky View Superior','Double bed or two single beds','An attic room beneath the sky','A compact fifth-floor room under the roof of the historic building. A skylight brings in daylight and opens a view of the sky.','Attic layout. State your bed preference when booking.'],
['Sky View Deluxe','Double or twin beds and a sofa','An attic room with an extra bed','A fifth-floor attic room with a sofa for an extra guest. Windows open onto the St Petersburg sky.','Ceiling shapes and bathroom configurations vary between rooms.'],
['Admiralty Superior','Double bed or two single beds','Admiralty and garden views','A room for two overlooking the Admiralty and Alexander Garden, with a desk and a coffee machine.','Rooms are on floors 2 and 4. Bed configuration is subject to availability.'],
['Apartment','180 × 200 cm double bed','A separate bedroom and full kitchen','A two-room apartment on the fourth floor with courtyard windows. The kitchen is equipped for preparing your own meals.','A separate bedroom and a kitchen with a dining area.'],
['Carlo Rossi Suite','Double bed and a sofa bed','A balcony overlooking the historic centre','A third-floor suite with a separate bedroom, living room, dressing room and balcony. Views of the Admiralty, garden and Palace Square.','Four-metre ceilings. Photographs show the particular version of this category.']
];
const amenityRu=['Wi-Fi','Кондиционер','Сейф','Телевизор','Халаты и тапочки','Душ','Чайная станция','Кофемашина','Ванна','Мини-кухня','Плита и микроволновая печь','Душ или ванна','Две комнаты','Детская кроватка по запросу','Кухня и обеденная зона','Ванна у окна','Кухня','Посудомоечная машина','Две ванные комнаты','Ванна и душ','Балкон','Гардеробная'];
const amenityEn=['Wi-Fi','Air conditioning','Safe','TV','Bathrobes and slippers','Shower','Tea station','Coffee machine','Bathtub','Kitchenette','Hob and microwave','Shower or bathtub','Two rooms','Cot on request','Kitchen and dining area','Bathtub by the window','Kitchen','Dishwasher','Two bathrooms','Bathtub and shower','Balcony','Dressing room'];
const extraAmenities={'Фен':'Hairdryer','Мини-холодильник':'Mini fridge','Письменный стол':'Desk','Питьевая вода':'Drinking water','Косметические средства':'Toiletries','Меню подушек':'Pillow menu','Номер для некурящих':'Non-smoking room'};
const captionsRu=['Кровать','Рабочая зона','Телевизор и стол','Окно во двор','Халат','Общий вид','Косметические принадлежности','Ванная комната','Рабочий стол','Детали рабочей зоны','Питьевая вода','Чайная станция','Сейф','Интерьер с зеркалом','Зона отдыха','Вариант с отдельными кроватями','Спальная зона','Прихожая','Вариант размещения с детской кроваткой','Детская кроватка','Кофемашина','Рабочее место','Мини-кухня','Кухонная зона','Вид из окна','Адмиралтейство вечером','Окно номера','Спальня в мансарде','Гостиная','Другой вариант интерьера','Спальня','Кухня и стол','Ванная комната с окном','Кухня в одном из вариантов','Окна гостиной','Другой вариант спальни','Обеденная зона','Кресла у окна','Общий вид мансарды','Прикроватный свет','Зеркало','Кухня','Душевая','Диван','Детали интерьера'];
const captionsEn=['Bed','Desk area','TV and desk','Courtyard window','Bathrobe','Room overview','Toiletries','Bathroom','Desk','Desk details','Drinking water','Tea station','Safe','Interior with a mirror','Seating area','Twin-bed configuration','Sleeping area','Entrance hall','Room with a cot','Cot','Coffee machine','Workspace','Kitchenette','Kitchen area','Window view','The Admiralty in the evening','Room window','Attic bedroom','Living room','Another interior layout','Bedroom','Kitchen and table','Bathroom with a window','Kitchen in one room configuration','Living-room windows','Another bedroom layout','Dining area','Armchairs by the window','Attic room overview','Bedside lighting','Mirror','Kitchen','Shower','Sofa','Interior details'];
export function englishRooms(rooms){return rooms.map((r,i)=>{const [name,beds,feature,description,note]=entries[i];return {...r,name,beds,feature,description,note,amenities:r.amenities.map(a=>{const n=amenityRu.indexOf(a);if(n<0&&!extraAmenities[a])throw new Error('Missing amenity translation: '+a);return n<0?extraAmenities[a]:amenityEn[n]}),photos:r.photos.map(p=>{const n=captionsRu.indexOf(p.caption);if(n<0)throw new Error('Missing caption translation: '+p.caption);return {...p,caption:captionsEn[n],alt:name+' — '+captionsEn[n]}})}})};
const hotelCaptions=[['Стойка регистрации','Reception'],['Гостиная у ресепшн','Lounge by reception'],['Детали гостеприимства','A warm welcome'],['Место для встреч','A place to meet'],['Внутренний двор','The inner courtyard'],['Цветы и мягкий свет','Flowers and soft light'],['Детали в ванной','Bathroom details'],['Светлый интерьер номера','A light-filled guest room'],['Петербург за окном','St Petersburg through the window'],['Спальня в тёплых тонах','A bedroom in warm colours'],['Время для чая','Time for tea'],['Особенные моменты','Special moments'],['Завтрак в номере','Breakfast in the room'],['Неспешное утро','A leisurely morning']];
export function hotelPhotos(lang='ru'){return hotelCaptions.map(([ru,en],i)=>({src:`/assets/hotel/${String(i+1).padStart(2,'0')}.webp`,alt:lang==='en'?en:ru,caption:lang==='en'?en:ru,group:i<5?'hotel':i===7||i===9?'rooms':'details',sourceUrl:`https://petr-hotel.com/images/startpage/3-2/${i+1}.jpg`}))}
export function allPhotos(rooms,lang){return [...hotelPhotos(lang),...rooms.flatMap(r=>r.photos.map(p=>({...p,caption:r.name+' · '+p.caption,group:'rooms',room:r.id})))];}
